name: Build SBOM and send to dt-api
description: |
  This action builds a CycloneDX Software Bill of Materials (SBOM) for a repository and sends it to a dt-api server.
inputs:
  dt-url:
    description: 'The URL of the dt-api server to send the SBOM to.'
    required: true
  api-key:
    description: 'The API key used to authenticate with the dt-api server.'
    required: true
  output-file:
    description: 'Token.'
    default: 'token for success'
    required: false
steps:
  - uses: actions/checkout@v2

  - name: Determine programming language
    id: determine-language
    run: |
      # Determine the repository language based on file extensions
      LANGUAGE=$(find . -type f -name "*.*" | sed 's/.*\.//' | sort | uniq -c | sort -nr | head -1 | awk '{print $2}')
      echo "language=${LANGUAGE}" >> $GITHUB_ENV
      echo "$LANGUAGE"
      echo "Language is $language"

  - name: Install dependencies for Node.js
    if: ${{ env.language == 'js' }}
    run: npm install

  - name: Create SBOM with CycloneDX
    id: sbom
    uses: AppThreat/cdxgen-action@v1
    with:
      output: ${{ inputs.output-file }}

  - name: Send SBOM to dt-api server
    env:
      API_KEY: ${{ inputs.api-key }}
      DT_URL: ${{ inputs.dt-url }}
    run: |
      REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
      TAG_REF=${{ github.ref }}
      if [[ "$TAG_REF" == "refs/tags/"* ]]; then
        VERSION=$(echo "$TAG_REF" | sed 's/refs\/tags\///')
      else
        VERSION="1.0.0"
      fi
      curl -k -X "POST" "$DT_URL" \
        -H "Content-Type: multipart/form-data" \
        -H "X-Api-Key: $API_KEY" \
        -F "autoCreate=true" \
        -F "projectName=$REPO_NAME" \
        -F "projectVersion=$VERSION" \
        -F "bom=@${{ inputs.output-file }}"
