name: Cryptosoft
author: Cryptosoft
description: 'Cryptosoft Generate SBOM and upload to OWASP Dependency Track'
inputs:
  dturl:
    description: 'OWASP Dependency Track URL of your organisation'
    required: true
outputs:
  token:
    description: 'Generated token that SBOM is uploaded'
    required: false
runs:
  using: 'node14'
   main: '.github/workflows/Nutrition.yml'
