name: Cryptosoft
author: Cryptosoft
name: Build SBOM and send to dt-api
description: Builds a CycloneDX SBOM and sends it to the OWASP Dependency-Track API
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Determine programming language
      id: determine-language 
      run: |      
        # Determine the repository language based on file extensions
        LANGUAGE=$(find . -type f -name "*.*" | sed 's/.*\.//' | sort | uniq -c | sort -nr | head -1 | awk '{print $2}')
        echo "language=${LANGUAGE}" >> $GITHUB_ENV
        echo "$LANGUAGE"
        echo "Language is $language"
    - name: Install dependencies for Node.js
      if: ${{env.language  == 'js' }}
      run: npm install
    - name: Create SBOM with CycloneDX
      id: sbom
      uses: AppThreat/cdxgen-action@v1
      with:
        output: './reports/bom.xml' 
    - name: Save SBOM to new file 
      id: saveBom
      run: |    
        echo -n "$(cat './reports/bom.xml')"  > output.xml   
    - name: Call API
      env:
        API_KEY: ${{ secrets.SECRET_OWASP_DT_KEY }}
        DT_URL: ${{ env.INPUT_DTURL }}
      run: | 
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2) 
        TAG_REF=${{ github.ref }}
        if [[ "$TAG_REF" == "refs/tags/"* ]]; then
          VERSION=$(echo "$TAG_REF" | sed 's/refs\/tags\///') 
        else
          VERSION="1.0.0" 
        fi 
        curl -k -X "POST" '$DT_URL' \
        -H 'Content-Type: multipart/form-data' \
        -H "X-Api-Key: $API_KEY" \
        -F "autoCreate=true" \
        -F "projectName=$REPO_NAME" \
        -F "projectVersion=$VERSION" \
        -F "bom=@output.xml"

