name: CryptosoftInc
description: This action builds a CycloneDX Format Software Bill of Materials (SBOM) for a repository and sends it to a OWASP DT Track.
inputs:
  dt-url:
    description: 'The URL of the Dependency-Track API server to send the SBOM a OWASP DT Track.
    required: true
  api-key:
    description: 'The API key used to authenticate with the Dependency-Track API server.'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2    
    - id: determine-language
      run: | 
        LANGUAGE=$(find . -type f -name "*.*" | sed 's/.*\.//' | sort | uniq -c | sort -nr | head -1 | awk '{print $2}')
        echo "language=${LANGUAGE}" >> $GITHUB_ENV
        echo "$LANGUAGE"
        echo "Language is $LANGUAGE"   
    - if: ${{ env.language == 'js' }}
      run: npm install  
    - id: sbom
      uses: AppThreat/cdxgen-action@v1
      with:
        output: './reports/bom.xml'
    - id: saveBom
      run: |    
        echo -n  "$(cat './reports/bom.xml')"  > output.xml   
      env:
        API_KEY: ${{ inputs.api-key }}
        DT_URL: ${{ inputs.dt-url }}
    - run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        TAG_REF=${{ github.ref }}
        if [[ "$TAG_REF" == "refs/tags/"* ]]; then
          VERSION=$(echo "$TAG_REF" | sed 's/refs\/tags\///')
        else
          VERSION="1.0.0"
        fi
        curl -k -X "POST" "$DT_URL" \
          -H "Content-Type: multipart/form-data" \
          -H "X-Api-Key: $API_KEY" \
          -F "autoCreate=true" \
          -F "projectName=$REPO_NAME" \
          -F "projectVersion=$VERSION" \
          -F "bom=@output.xml"

