name: CryptosoftInc CycloneDX SBOM Generator
description: This action builds a CycloneDX Format SBOM for a repository and sends it to an OWASP Dependency-Track server.
inputs:
  dt-url:
    description: 'The URL of the OWASP Dependency-Track API server to send the SBOM to.'
    required: true
  api-key:
    description: 'The API key used to authenticate with the OWASP Dependency-Track API server.'
    required: true
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Determine programming language
      id: determine-language
      run: |
        LANGUAGE=$(find . -type f -name "*.*" | sed 's/.*\.//' | sort | uniq -c | sort -nr | head -1 | awk '{print $2}')
        echo "language=${LANGUAGE}" >> $GITHUB_ENV
        echo "Language is $LANGUAGE"
    - name: Install dependencies for Node.js
      if: ${{ env.language == 'js' }}
      run: npm install
    - name: Create SBOM with CycloneDX
      id: sbom
      uses: AppThreat/cdxgen-action@v1
      with:
        output: './reports/bom.xml'
    - name: Save SBOM to new file
      id: saveBom
      run: |
        echo -n "$(cat './reports/bom.xml')"  > output.xml
      env:
        API_KEY: ${{ inputs.api-key }}
        DT_URL: ${{ inputs.dt-url }}
    - name: Send SBOM to OWASP Dependency-Track server
      env:
        API_KEY: ${{ inputs.api-key }}
        DT_URL: ${{ inputs.dt-url }}
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        TAG_REF=${{ github.ref }}
        if [[ "$TAG_REF" == "refs/tags/"* ]]; then
          VERSION=$(echo "$TAG_REF" | sed 's/refs\/tags\///')
        else
          VERSION="1.0.0"
        fi
        curl -k -X "POST" "$DT_URL" \
          -H "Content-Type: multipart/form-data" \
          -H "X-Api-Key: $API_KEY" \
          -F "autoCreate=true" \
          -F "projectName=$REPO_NAME" \
          -F "projectVersion=$VERSION" \
          -F "bom=@output.xml"
